### PR TITLE
Added licenses, etc. and Code Master

### PR DESCRIPTION
**Pull request by penyuan**
Tried my best to find license info for each game, when none could be found I assumed its proprietary. Added price and platforms when possible. Also added Code Master board game.

### CODE REVIEW

**Comment by stared** [comment]
However, e.g. https://vim-adventures.com/ is not free (actually, it's expensive).

(And IMHO it might be wiser to refrain from mentioning actual prices - they are changing, and this repo is intended to last longer than a year.)

**Comment by penyuan** [comment]
Good point about the price, I agree. I've removed price information from all games. Hope it works now?

**Comment by stared** [comment]
Great, merging!

(Not sure if it is not better to write somewhere that licence is proprietary unless stated otherwise - right now its a bit of visual noise.)

**Comment by stared** [comment]
EDIT: @penyuan  I had to revert (made a marge too soon), sry for that.

But then saw `proprietary` in a number of products 
Adding like `proprietary` when licence is unknown (in some cases most likely author does not bother) is hardly helpful.
In this case - could you just add licence when there is open-source one (repos, if they exist, are always helpful)?

For price - I meant just mentioning it $, without actual amount. Changing price for sth to free does not happen often (and here it may be useful).

**Comment by penyuan** [comment]
Hi! Sorry I've been really busy with Real Life (TM). :)

Regarding the `proprietary` licenses, I added them because it *is* important information. When no specific license is specified for a software, it is legally proprietary by default and this is important for people to know. So I don't think we should avoid saying that.

As for price, I agree that maybe just stating "$" vs "free of charge" is enough.

Would you like a new pull request? Thanks!!

**Comment by stared** [comment]
@penyuan 

I tied to merge back your changes, but it turns I couldn't do that (since Git thought that there are old, since they have been updated since). Sorry for being trigger-happy - I hope I made no harm. In any case, I am looking forward 

For `proprietary` - there are two issues here:

* for Markdown file I try to keeps thing minimal; as most games are video games, I don't write it; if most are proprietary, I would add some footnote that it's default (and only mention if they aren't)
* in general, knowing that license status is unknown is also a valuable information (especially for small games by one person, as licence clarification may actually mean open-sourcing them)

So, how about writing in bullet points, without keywords (like: `license: ` or `platform: `), in this minimalistic form?

* Android ($), iOS ($), web (free)
* open source (MIT): http://github.com/wfsdfds/sdsdf

If there is repo, of course it can be "proprietary" (if stated explicitly!) or "unknown license status".
For just "proprietary" without repos, I would prefer to drop this line to safe space. Is it fine? :)

With respect to YAML, in which one can be explicit, as it is only a data format for some more graphical presentation, see example here: https://github.com/stared/science-based-games-list/blob/yamlization/games.yaml (it's very easy: http://yaml.org/)

**Comment by penyuan** [comment]
Hi!! Sounds like a good compromise, I think just one sentence or bullet point near the first couple of paragraphs that the games are proprietary unless specifically stated otherwise should be enough. And I agree with the "Android ($), iOS ($), web (free)" format.

I'll take a look if I get find my original pull request and redo it. Otherwise I might go straight to a YAML version with that information (price, license, repo, etc.). Thanks!

**Comment by penyuan** [comment]
I've created a new pull request.

**Pull request merged**
