### PR TITLE
Adding Quantum Marble Maze

### PR DESCRIPTION
**Pull request by fiftysevendegreesofrad**
I put it with the other quantum games, hope that's cool

### CODE REVIEW

**Comment by stared** [comment]
@fiftysevendegreesofrad  Looks promising, but is there a more user-friendly (and safer!) way to play than to download and run a `jar` file?

**Comment by fiftysevendegreesofrad** [comment]
What would you suggest? Make it a paid app on Steam or similar so you can say it's a trusted distribution channel?

**Comment by stared** [comment]
It may not that easy to get on Steam right away.

Yet, even from practical adoption perspective, something which is executable (`.exe`, `.App`, etc) - both way easier to use and looking more trustworthy.

(Or even better - if it can be run through the browser interface with out installing anything. No idea if it is easy to make it from Java. All gamedev experience I have is Unity3D (C#) and JavaScript.)

**Comment by stared** [comment]
In any case, adding it. But note that without easy way to run, not many people will run it.

**Comment by fiftysevendegreesofrad** [comment]
Thank you for the merge. Why do you think exe is more trustworthy?

**Pull request merged**
